apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-170307825
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-170307825
    app.kubernetes.io/part-of: test-app-170307825
  name: java-quarkus-170307825
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-170307825
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-170307825
    spec:
      containers:
      - image: quay.io/hacdev/a4pbsrz3-tenant/test-app-170307825/java-quarkus-170307825@sha256:1ebfde9f8511bed58605a4bdd186ff4b6e7a525305cf3c8f2a4eb0d624d29542
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
